---

name: Build

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - name: linux
            os: ubuntu-latest
          - name: windows
            os: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: >
          sudo apt-get update
          &&
          sudo apt-get install
          libsdl2-dev
          libsdl2-image-dev

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          build-type: Release
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest

      - name: Configure CMake
        run: >
          cmake
          -D CMAKE_BUILD_TYPE=Release
          -D OPENLIERO_BUILD_TCTOOL=ON

      - name: Build
        run: >
          cmake
          --build .
          --config Release
          --parallel 4

      - name: Move executable (Windows)
        if: runner.os == 'Windows'
        run: >
          Move-Item
          -Path Release/openliero.exe,Release/tctool.exe
          -Destination .

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-build
          path: |
            openliero*
            tctool*
            Resources
            Setups
            Profiles
            TC

  release:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: linux-build

      - uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: windows-build

      - name: Create archive (Linux)
        run: |
          chmod +x linux-build/openliero linux-build/tctool
          cd linux-build
          tar cfJ liero-linux-x64-${{ github.sha }}.tar.xz *
          cd ..

      - name: Create archive (Windows)
        run: |
          curl -L \
          -o windows-build/sdl2-win-x64.zip \
          https://github.com/libsdl-org/SDL/releases/download/release-2.30.6/SDL2-2.30.6-win32-x64.zip
          curl -L \
          -o windows-build/sdl2_image-win-x64.zip \
          https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.2/SDL2_image-2.8.2-win32-x64.zip
          cd windows-build
          unzip sdl2-win-x64.zip
          rm -rf sdl2-win-x64.zip
          unzip sdl2_image-win-x64.zip
          rm -rf sdl2_image-win-x64.zip optional
          mv README.txt README-SDL_image.txt
          zip -r liero-windows-x64-${{ github.sha }}.zip .
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}-${{ github.sha }}
          files: |
            linux-build/liero-linux-x64-${{ github.sha }}.tar.xz
            windows-build/liero-windows-x64-${{ github.sha }}.zip
