name: Build
on: [push, workflow_dispatch]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      #- uses: libsdl-org/setup-sdl@main
      #  id: sdl
      #  with:
      #    install-linux-dependencies: true
      #    version: 2-latest
      #    version-sdl-image: 2-latest
      - name: Setup SDL2 frameworks
        uses: BrettDong/setup-sdl2-frameworks@main
        with:
          sdl2: latest
          sdl2-ttf: none
          sdl2-image: latest
          sdl2-mixer: none
          sdl2-net: none
      - name: Prepare build
        run: cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
      - name: Build
        run: make
  build-ubuntu:
    # this is later than ubuntu-latest
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # does not work, see: https://github.com/libsdl-org/setup-sdl/issues/23
      #- uses: libsdl-org/setup-sdl@main
      #  id: sdl
      #  with:
      #    install-linux-dependencies: true
      #    version: 2-latest
      #    version-sdl-image: 2-latest
      - name: Install dependencies
        run: sudo apt-get install -y libsdl2-dev libsdl2-image-dev
      - name: Prepare build
        run: cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
      - name: Build
        run: make
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest
      - name: Prepare build
        run: cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022"
      - name: Build
        run: cmake --build . --config Release
