name: Build
on: [push, workflow_dispatch]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest
      - name: Prepare build
        run: cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
      - name: Build
        run: make
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # does not work, see: https://github.com/libsdl-org/setup-sdl/issues/23
      #- uses: libsdl-org/setup-sdl@main
      #  id: sdl
      #  with:
      #    install-linux-dependencies: true
      #    version: 2-latest
      #    version-sdl-image: 2-latest
      - name: Install dependencies
        run: sudo apt-get install -y libsdl2-dev libsdl2-image-dev
      - name: Prepare build
        run: cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
      - name: Build
        run: make
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest
      - name: Prepare build
        run: cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022"
      - name: Build
        run: cmake --build . --config Release
